### ISSUE TITLE
How to train Qwen2.5-VL-7B-Instruct

### ISSUE THREAD

**Issue by xddun** [om-ai-lab/VLM-R1#215]
80G A800, five gpus , Can you give me a configuration? I always get an out-of-memory error with the current configuration I'm using：

```
cd src/open-r1-multimodal

export DEBUG_MODE="true"

RUN_NAME="Qwen2.5-VL-7B-GRPO-GUI_multi-image"
export LOG_PATH="./debug_log_$RUN_NAME.txt"

torchrun --nproc_per_node=5 \
    --nnodes=1 \
    --node_rank=${RANK} \
    --master_addr=${MASTER_ADDR} \
    --master_port=${MASTER_PORT} \
    src/open_r1/grpo_jsonl.py \
    --deepspeed local_scripts/zero3.json \
    --output_dir /output_qwen25vl7b_xd/$RUN_NAME \
    --model_name_or_path /Qwen2.5-VL-7B-Instruct \
    --dataset_name none \
    --image_folders /tasks-json-ui-doctor/tasks_json \
    --data_file_paths /tasks-json-ui-doctor/ui_doctor_dataset.jsonl \
    --freeze_vision_modules true \
    --max_prompt_length 4096 \
    --num_generations 5 \
    --per_device_train_batch_size 1 \
    --gradient_accumulation_steps 1 \
    --logging_steps 1 \
    --bf16 \
    --torch_dtype bfloat16 \
    --data_seed 42 \
    --report_to "tensorboard" \
    --logging_dir "/mnt/cluster123"
    --gradient_checkpointing true \
    --attn_implementation flash_attention_2 \
    --num_train_epochs 2 \
    --run_name $RUN_NAME \
    --save_steps 100 \
    --save_only_model true
```

error：

[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/transformers/models/qwen2_5_vl/modeling_qwen2_5_vl.py", line 320, in forward
[rank0]:     attn_output = F.scaled_dot_product_attention(q, k, v, attention_mask, dropout_p=0.0)
[rank0]:                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]: torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 119.03 GiB. GPU 0 has a total capacity of 79.33 GiB of which 40.16 GiB is free. Process 490553 has 39.16 GiB memory in use. Of the allocated memory 37.81 GiB is allocated by PyTorch, and 322.73 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

**Comment by xddun** [comment]
My instruction issue has been resolved.

**Comment by fansticOne** [comment]
> My instruction issue has been resolved.

How did you solve it? I encountered same issue with A800,80G,2GPUS,the run script that I use is run_scrpits/run_grpo_gui.sh.
