### ISSUE TITLE
Miss AutoModelForCausalLM

### ISSUE THREAD

**Issue by yuanzhao-CVLAB** [om-ai-lab/VLM-R1#338]
/bin/bash /home/zhaoyuan/code/Other/VLM-R1/run_scripts/run_grpo_rec.sh
REPO_HOME: /home/zhaoyuan/code/Other/VLM-R1
data_paths: /home/ubuntun/disk7T/zy/data/RefCoco/rec_jsons_processed/refcoco_train.jsonl:/home/ubuntun/disk7T/zy/data/RefCoco/rec_jsons_processed/refcocop_train.jsonl:/home/ubuntun/disk7T/zy/data/RefCoco/rec_jsons_processed/refcocog_train.jsonl
image_folders: /home/ubuntun/disk7T/zy/data/RefCoco:/home/ubuntun/disk7T/zy/data/RefCoco:/home/ubuntun/disk7T/zy/data/RefCoco
W0827 11:46:43.030000 28212 site-packages/torch/distributed/run.py:793] 
W0827 11:46:43.030000 28212 site-packages/torch/distributed/run.py:793] *****************************************
W0827 11:46:43.030000 28212 site-packages/torch/distributed/run.py:793] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W0827 11:46:43.030000 28212 site-packages/torch/distributed/run.py:793] *****************************************
[2025-08-27 11:46:46,417] [INFO] [real_accelerator.py:219:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2025-08-27 11:46:46,439] [INFO] [real_accelerator.py:219:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2025-08-27 11:46:46,452] [INFO] [real_accelerator.py:219:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2025-08-27 11:46:46,533] [INFO] [real_accelerator.py:219:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2025-08-27 11:46:46,535] [INFO] [real_accelerator.py:219:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2025-08-27 11:46:46,545] [INFO] [real_accelerator.py:219:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2025-08-27 11:46:46,553] [INFO] [real_accelerator.py:219:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2025-08-27 11:46:46,598] [INFO] [real_accelerator.py:219:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2025-08-27 11:46:48,205] [INFO] [comm.py:652:init_distributed] cdb=None
[2025-08-27 11:46:48,237] [INFO] [comm.py:652:init_distributed] cdb=None
zero3 is used, qwen2_5vl forward monkey patch is applied
using vlm module: Qwen2VLModule
reward_funcs: [<function Qwen2VLModule.iou_reward at 0x7c364e3c68c0>, <function Qwen2VLModule.format_reward_rec at 0x7c364e3c6830>]
zero3 is used, qwen2_5vl forward monkey patch is applied
using vlm module: Qwen2VLModule
reward_funcs: [<function Qwen2VLModule.iou_reward at 0x799b341ba8c0>, <function Qwen2VLModule.format_reward_rec at 0x799b341ba830>]
[2025-08-27 11:46:48,433] [INFO] [comm.py:652:init_distributed] cdb=None
[2025-08-27 11:46:48,448] [INFO] [comm.py:652:init_distributed] cdb=None
[2025-08-27 11:46:48,448] [INFO] [comm.py:683:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
[2025-08-27 11:46:48,489] [INFO] [comm.py:652:init_distributed] cdb=None
[2025-08-27 11:46:48,519] [INFO] [comm.py:652:init_distributed] cdb=None
[2025-08-27 11:46:48,538] [INFO] [comm.py:652:init_distributed] cdb=None
[2025-08-27 11:46:48,612] [INFO] [comm.py:652:init_distributed] cdb=None
zero3 is used, qwen2_5vl forward monkey patch is applied
using vlm module: Qwen2VLModule
reward_funcs: [<function Qwen2VLModule.iou_reward at 0x7adaa6baaa70>, <function Qwen2VLModule.format_reward_rec at 0x7adaa6baa9e0>]
zero3 is used, qwen2_5vl forward monkey patch is applied
using vlm module: Qwen2VLModule
reward_funcs: [<function Qwen2VLModule.iou_reward at 0x754d39cce830>, <function Qwen2VLModule.format_reward_rec at 0x754d39cce7a0>]
zero3 is used, qwen2_5vl forward monkey patch is applied
using vlm module: Qwen2VLModule
reward_funcs: [<function Qwen2VLModule.iou_reward at 0x70f23e4be8c0>, <function Qwen2VLModule.format_reward_rec at 0x70f23e4be830>]
zero3 is used, qwen2_5vl forward monkey patch is applied
using vlm module: Qwen2VLModule
reward_funcs: [<function Qwen2VLModule.iou_reward at 0x7c8a31fd6830>, <function Qwen2VLModule.format_reward_rec at 0x7c8a31fd67a0>]
zero3 is used, qwen2_5vl forward monkey patch is applied
using vlm module: Qwen2VLModule
reward_funcs: [<function Qwen2VLModule.iou_reward at 0x796c477cea70>, <function Qwen2VLModule.format_reward_rec at 0x796c477ce9e0>]
zero3 is used, qwen2_5vl forward monkey patch is applied
using vlm module: Qwen2VLModule
reward_funcs: [<function Qwen2VLModule.iou_reward at 0x79bf9cabe830>, <function Qwen2VLModule.format_reward_rec at 0x79bf9cabe7a0>]
Map (num_proc=8): 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 321327/321327 [00:08<00:00, 38743.96 examples/s]
using trainer: VLMGRPOTrainer
Map (num_proc=8): 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 321327/321327 [00:08<00:00, 37484.08 examples/s]
using trainer: VLMGRPOTrainer
Map (num_proc=8): 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 321327/321327 [00:08<00:00, 37363.10 examples/s]
using trainer: VLMGRPOTrainer
Map (num_proc=8): 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 321327/321327 [00:08<00:00, 36454.17 examples/s]
using trainer: VLMGRPOTrainer
Map (num_proc=8): 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 321327/321327 [00:08<00:00, 36567.28 examples/s]
Map (num_proc=8): 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 321327/321327 [00:08<00:00, 36049.68 examples/s]
using trainer: VLMGRPOTrainer
using trainer: VLMGRPOTrainer
Map (num_proc=8): 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 321327/321327 [00:08<00:00, 36404.74 examples/s]
using trainer: VLMGRPOTrainer
Map (num_proc=8): 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 321327/321327 [00:08<00:00, 35868.46 examples/s]
using trainer: VLMGRPOTrainer
[2025-08-27 11:47:01,449] [INFO] [config.py:733:__init__] Config mesh_device None world_size = 8
You are attempting to use Flash Attention 2.0 with a model not initialized on GPU. Make sure to move the model to GPU after initializing it on CPU with `model.to('cuda')`.
[2025-08-27 11:47:01,472] [INFO] [config.py:733:__init__] Config mesh_device None world_size = 8
You are attempting to use Flash Attention 2.0 with a model not initialized on GPU. Make sure to move the model to GPU after initializing it on CPU with `model.to('cuda')`.
[2025-08-27 11:47:02,241] [INFO] [config.py:733:__init__] Config mesh_device None world_size = 8
You are attempting to use Flash Attention 2.0 with a model not initialized on GPU. Make sure to move the model to GPU after initializing it on CPU with `model.to('cuda')`.
[2025-08-27 11:47:02,291] [INFO] [config.py:733:__init__] Config mesh_device None world_size = 8
You are attempting to use Flash Attention 2.0 with a model not initialized on GPU. Make sure to move the model to GPU after initializing it on CPU with `model.to('cuda')`.
[2025-08-27 11:47:02,316] [INFO] [config.py:733:__init__] Config mesh_device None world_size = 8
You are attempting to use Flash Attention 2.0 with a model not initialized on GPU. Make sure to move the model to GPU after initializing it on CPU with `model.to('cuda')`.
[2025-08-27 11:47:02,463] [INFO] [config.py:733:__init__] Config mesh_device None world_size = 8
You are attempting to use Flash Attention 2.0 with a model not initialized on GPU. Make sure to move the model to GPU after initializing it on CPU with `model.to('cuda')`.
[2025-08-27 11:47:02,776] [INFO] [config.py:733:__init__] Config mesh_device None world_size = 8
You are attempting to use Flash Attention 2.0 with a model not initialized on GPU. Make sure to move the model to GPU after initializing it on CPU with `model.to('cuda')`.
[2025-08-27 11:47:03,131] [INFO] [config.py:733:__init__] Config mesh_device None world_size = 8
You are attempting to use Flash Attention 2.0 with a model not initialized on GPU. Make sure to move the model to GPU after initializing it on CPU with `model.to('cuda')`.
Loading checkpoint shards:   0%|                                                                                                                                       | 0/2 [00:00<?, ?it/s][2025-08-27 11:47:04,134] [INFO] [partition_parameters.py:348:__exit__] finished initializing model - num_params = 825, num_elems = 4.07B
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:03<00:00,  1.92s/it]
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:03<00:00,  1.93s/it]
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:03<00:00,  1.95s/it]
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:03<00:00,  1.94s/it]
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:03<00:00,  1.93s/it]
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:03<00:00,  1.95s/it]
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:03<00:00,  1.95s/it]
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:03<00:00,  1.96s/it]
Total trainable parameters: 0
Total trainable parameters: 0
Total trainable parameters: 0
Total trainable parameters: 0
Total trainable parameters: 0
Total trainable parameters: 0
Total trainable parameters: 0
Total trainable parameters: 0
[rank4]: Traceback (most recent call last):
[rank4]:   File "/home/ubuntun/disk7T/zy/code/Other/VLM-R1/src/open-r1-multimodal/src/open_r1/grpo_jsonl.py", line 1073, in <module>
[rank4]:     main(script_args, training_args, model_args)
[rank4]:   File "/home/ubuntun/disk7T/zy/code/Other/VLM-R1/src/open-r1-multimodal/src/open_r1/grpo_jsonl.py", line 1040, in main
[rank4]:     trainer = trainer_cls(
[rank4]:   File "/home/ubuntun/disk7T/zy/code/Other/VLM-R1/src/open-r1-multimodal/src/open_r1/trainer/grpo_trainer.py", line 301, in __init__
[rank4]:     self.ref_model = AutoModelForCausalLM.from_pretrained(model_id, **model_init_kwargs)
[rank4]:   File "/home/ubuntun/anaconda3/envs/VLM/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 567, in from_pretrained
[rank4]:     raise ValueError(
[rank4]: ValueError: Unrecognized configuration class <class 'transformers.models.qwen2_5_vl.configuration_qwen2_5_vl.Qwen2_5_VLConfig'> for this kind of AutoModel: AutoModelForCausalLM.
[rank4]: Model type should be one of AriaTextConfig, BambaConfig, BartConfig, BertConfig, BertGenerationConfig, BigBirdConfig, BigBirdPegasusConfig, BioGptConfig, BlenderbotConfig, BlenderbotSmallConfig, BloomConfig, CamembertConfig, LlamaConfig, CodeGenConfig, CohereConfig, Cohere2Config, CpmAntConfig, CTRLConfig, Data2VecTextConfig, DbrxConfig, DiffLlamaConfig, ElectraConfig, Emu3Config, ErnieConfig, FalconConfig, FalconMambaConfig, FuyuConfig, GemmaConfig, Gemma2Config, GitConfig, GlmConfig, GotOcr2Config, GPT2Config, GPT2Config, GPTBigCodeConfig, GPTNeoConfig, GPTNeoXConfig, GPTNeoXJapaneseConfig, GPTJConfig, GraniteConfig, GraniteMoeConfig, GraniteMoeSharedConfig, HeliumConfig, JambaConfig, JetMoeConfig, LlamaConfig, MambaConfig, Mamba2Config, MarianConfig, MBartConfig, MegaConfig, MegatronBertConfig, MistralConfig, MixtralConfig, MllamaConfig, MoshiConfig, MptConfig, MusicgenConfig, MusicgenMelodyConfig, MvpConfig, NemotronConfig, OlmoConfig, Olmo2Config, OlmoeConfig, OpenLlamaConfig, OpenAIGPTConfig, OPTConfig, PegasusConfig, PersimmonConfig, PhiConfig, Phi3Config, PhimoeConfig, PLBartConfig, ProphetNetConfig, QDQBertConfig, Qwen2Config, Qwen2MoeConfig, RecurrentGemmaConfig, ReformerConfig, RemBertConfig, RobertaConfig, RobertaPreLayerNormConfig, RoCBertConfig, RoFormerConfig, RwkvConfig, Speech2Text2Config, StableLmConfig, Starcoder2Config, TransfoXLConfig, TrOCRConfig, WhisperConfig, XGLMConfig, XLMConfig, XLMProphetNetConfig, XLMRobertaConfig, XLMRobertaXLConfig, XLNetConfig, XmodConfig, ZambaConfig, Zamba2Config.
[rank1]: Traceback (most recent call last):
[rank1]:   File "/home/ubuntun/disk7T/zy/code/Other/VLM-R1/src/open-r1-multimodal/src/open_r1/grpo_jsonl.py", line 1073, in <module>
[rank1]:     main(script_args, training_args, model_args)
[rank1]:   File "/home/ubuntun/disk7T/zy/code/Other/VLM-R1/src/open-r1-multimodal/src/open_r1/grpo_jsonl.py", line 1040, in main
[rank1]:     trainer = trainer_cls(
[rank1]:   File "/home/ubuntun/disk7T/zy/code/Other/VLM-R1/src/open-r1-multimodal/src/open_r1/trainer/grpo_trainer.py", line 301, in __init__
[rank1]:     self.ref_model = AutoModelForCausalLM.from_pretrained(model_id, **model_init_kwargs)
[rank1]:   File "/home/ubuntun/anaconda3/envs/VLM/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 567, in from_pretrained
[rank1]:     raise ValueError(
[rank1]: ValueError: Unrecognized configuration class <class 'transformers.models.qwen2_5_vl.configuration_qwen2_5_vl.Qwen2_5_VLConfig'> for this kind of AutoModel: AutoModelForCausalLM.
[rank1]: Model type should be one of AriaTextConfig, BambaConfig, BartConfig, BertConfig, BertGenerationConfig, BigBirdConfig, BigBirdPegasusConfig, BioGptConfig, BlenderbotConfig, BlenderbotSmallConfig, BloomConfig, CamembertConfig, LlamaConfig, CodeGenConfig, CohereConfig, Cohere2Config, CpmAntConfig, CTRLConfig, Data2VecTextConfig, DbrxConfig, DiffLlamaConfig, ElectraConfig, Emu3Config, ErnieConfig, FalconConfig, FalconMambaConfig, FuyuConfig, GemmaConfig, Gemma2Config, GitConfig, GlmConfig, GotOcr2Config, GPT2Config, GPT2Config, GPTBigCodeConfig, GPTNeoConfig, GPTNeoXConfig, GPTNeoXJapaneseConfig, GPTJConfig, GraniteConfig, GraniteMoeConfig, GraniteMoeSharedConfig, HeliumConfig, JambaConfig, JetMoeConfig, LlamaConfig, MambaConfig, Mamba2Config, MarianConfig, MBartConfig, MegaConfig, MegatronBertConfig, MistralConfig, MixtralConfig, MllamaConfig, MoshiConfig, MptConfig, MusicgenConfig, MusicgenMelodyConfig, MvpConfig, NemotronConfig, OlmoConfig, Olmo2Config, OlmoeConfig, OpenLlamaConfig, OpenAIGPTConfig, OPTConfig, PegasusConfig, PersimmonConfig, PhiConfig, Phi3Config, PhimoeConfig, PLBartConfig, ProphetNetConfig, QDQBertConfig, Qwen2Config, Qwen2MoeConfig, RecurrentGemmaConfig, ReformerConfig, RemBertConfig, RobertaConfig, RobertaPreLayerNormConfig, RoCBertConfig, RoFormerConfig, RwkvConfig, Speech2Text2Config, StableLmConfig, Starcoder2Config, TransfoXLConfig, TrOCRConfig, WhisperConfig, XGLMConfig, XLMConfig, XLMProphetNetConfig, XLMRobertaConfig, XLMRobertaXLConfig, XLNetConfig, XmodConfig, ZambaConfig, Zamba2Config.
[rank6]: Traceback (most recent call last):
[rank6]:   File "/home/ubuntun/disk7T/zy/code/Other/VLM-R1/src/open-r1-multimodal/src/open_r1/grpo_jsonl.py", line 1073, in <module>
[rank6]:     main(script_args, training_args, model_args)
[rank6]:   File "/home/ubuntun/disk7T/zy/code/Other/VLM-R1/src/open-r1-multimodal/src/open_r1/grpo_jsonl.py", line 1040, in main
[rank6]:     trainer = trainer_cls(
[rank6]:   File "/home/ubuntun/disk7T/zy/code/Other/VLM-R1/src/open-r1-multimodal/src/open_r1/trainer/grpo_trainer.py", line 301, in __init__
[rank6]:     self.ref_model = AutoModelForCausalLM.from_pretrained(model_id, **model_init_kwargs)
[rank6]:   File "/home/ubuntun/anaconda3/envs/VLM/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 567, in from_pretrained
[rank6]:     raise ValueError(
[rank6]: ValueError: Unrecognized configuration class <class 'transformers.models.qwen2_5_vl.configuration_qwen2_5_vl.Qwen2_5_VLConfig'> for this kind of AutoModel: AutoModelForCausalLM.
[rank6]: Model type should be one of AriaTextConfig, BambaConfig, BartConfig, BertConfig, BertGenerationConfig, BigBirdConfig, BigBirdPegasusConfig, BioGptConfig, BlenderbotConfig, BlenderbotSmallConfig, BloomConfig, CamembertConfig, LlamaConfig, CodeGenConfig, CohereConfig, Cohere2Config, CpmAntConfig, CTRLConfig, Data2VecTextConfig, DbrxConfig, DiffLlamaConfig, ElectraConfig, Emu3Config, ErnieConfig, FalconConfig, FalconMambaConfig, FuyuConfig, GemmaConfig, Gemma2Config, GitConfig, GlmConfig, GotOcr2Config, GPT2Config, GPT2Config, GPTBigCodeConfig, GPTNeoConfig, GPTNeoXConfig, GPTNeoXJapaneseConfig, GPTJConfig, GraniteConfig, GraniteMoeConfig, GraniteMoeSharedConfig, HeliumConfig, JambaConfig, JetMoeConfig, LlamaConfig, MambaConfig, Mamba2Config, MarianConfig, MBartConfig, MegaConfig, MegatronBertConfig, MistralConfig, MixtralConfig, MllamaConfig, MoshiConfig, MptConfig, MusicgenConfig, MusicgenMelodyConfig, MvpConfig, NemotronConfig, OlmoConfig, Olmo2Config, OlmoeConfig, OpenLlamaConfig, OpenAIGPTConfig, OPTConfig, PegasusConfig, PersimmonConfig, PhiConfig, Phi3Config, PhimoeConfig, PLBartConfig, ProphetNetConfig, QDQBertConfig, Qwen2Config, Qwen2MoeConfig, RecurrentGemmaConfig, ReformerConfig, RemBertConfig, RobertaConfig, RobertaPreLayerNormConfig, RoCBertConfig, RoFormerConfig, RwkvConfig, Speech2Text2Config, StableLmConfig, Starcoder2Config, TransfoXLConfig, TrOCRConfig, WhisperConfig, XGLMConfig, XLMConfig, XLMProphetNetConfig, XLMRobertaConfig, XLMRobertaXLConfig, XLNetConfig, XmodConfig, ZambaConfig, Zamba2Config.
[rank5]: Traceback (most recent call last):
[rank5]:   File "/home/ubuntun/disk7T/zy/code/Other/VLM-R1/src/open-r1-multimodal/src/open_r1/grpo_jsonl.py", line 1073, in <module>
[rank5]:     main(script_args, training_args, model_args)
[rank5]:   File "/home/ubuntun/disk7T/zy/code/Other/VLM-R1/src/open-r1-multimodal/src/open_r1/grpo_jsonl.py", line 1040, in main
[rank5]:     trainer = trainer_cls(
[rank5]:   File "/home/ubuntun/disk7T/zy/code/Other/VLM-R1/src/open-r1-multimodal/src/open_r1/trainer/grpo_trainer.py", line 301, in __init__
[rank5]:     self.ref_model = AutoModelForCausalLM.from_pretrained(model_id, **model_init_kwargs)
[rank5]:   File "/home/ubuntun/anaconda3/envs/VLM/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 567, in from_pretrained
[rank5]:     raise ValueError(
[rank5]: ValueError: Unrecognized configuration class <class 'transformers.models.qwen2_5_vl.configuration_qwen2_5_vl.Qwen2_5_VLConfig'> for this kind of AutoModel: AutoModelForCausalLM.
[rank5]: Model type should be one of AriaTextConfig, BambaConfig, BartConfig, BertConfig, BertGenerationConfig, BigBirdConfig, BigBirdPegasusConfig, BioGptConfig, BlenderbotConfig, BlenderbotSmallConfig, BloomConfig, CamembertConfig, LlamaConfig, CodeGenConfig, CohereConfig, Cohere2Config, CpmAntConfig, CTRLConfig, Data2VecTextConfig, DbrxConfig, DiffLlamaConfig, ElectraConfig, Emu3Config, ErnieConfig, FalconConfig, FalconMambaConfig, FuyuConfig, GemmaConfig, Gemma2Config, GitConfig, GlmConfig, GotOcr2Config, GPT2Config, GPT2Config, GPTBigCodeConfig, GPTNeoConfig, GPTNeoXConfig, GPTNeoXJapaneseConfig, GPTJConfig, GraniteConfig, GraniteMoeConfig, GraniteMoeSharedConfig, HeliumConfig, JambaConfig, JetMoeConfig, LlamaConfig, MambaConfig, Mamba2Config, MarianConfig, MBartConfig, MegaConfig, MegatronBertConfig, MistralConfig, MixtralConfig, MllamaConfig, MoshiConfig, MptConfig, MusicgenConfig, MusicgenMelodyConfig, MvpConfig, NemotronConfig, OlmoConfig, Olmo2Config, OlmoeConfig, OpenLlamaConfig, OpenAIGPTConfig, OPTConfig, PegasusConfig, PersimmonConfig, PhiConfig, Phi3Config, PhimoeConfig, PLBartConfig, ProphetNetConfig, QDQBertConfig, Qwen2Config, Qwen2MoeConfig, RecurrentGemmaConfig, ReformerConfig, RemBertConfig, RobertaConfig, RobertaPreLayerNormConfig, RoCBertConfig, RoFormerConfig, RwkvConfig, Speech2Text2Config, StableLmConfig, Starcoder2Config, TransfoXLConfig, TrOCRConfig, WhisperConfig, XGLMConfig, XLMConfig, XLMProphetNetConfig, XLMRobertaConfig, XLMRobertaXLConfig, XLNetConfig, XmodConfig, ZambaConfig, Zamba2Config.
[rank3]: Traceback (most recent call last):
[rank3]:   File "/home/ubuntun/disk7T/zy/code/Other/VLM-R1/src/open-r1-multimodal/src/open_r1/grpo_jsonl.py", line 1073, in <module>
[rank3]:     main(script_args, training_args, model_args)
[rank3]:   File "/home/ubuntun/disk7T/zy/code/Other/VLM-R1/src/open-r1-multimodal/src/open_r1/grpo_jsonl.py", line 1040, in main
[rank3]:     trainer = trainer_cls(
[rank3]:   File "/home/ubuntun/disk7T/zy/code/Other/VLM-R1/src/open-r1-multimodal/src/open_r1/trainer/grpo_trainer.py", line 301, in __init__
[rank3]:     self.ref_model = AutoModelForCausalLM.from_pretrained(model_id, **model_init_kwargs)
[rank3]:   File "/home/ubuntun/anaconda3/envs/VLM/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 567, in from_pretrained
[rank3]:     raise ValueError(
[rank3]: ValueError: Unrecognized configuration class <class 'transformers.models.qwen2_5_vl.configuration_qwen2_5_vl.Qwen2_5_VLConfig'> for this kind of AutoModel: AutoModelForCausalLM.
[rank3]: Model type should be one of AriaTextConfig, BambaConfig, BartConfig, BertConfig, BertGenerationConfig, BigBirdConfig, BigBirdPegasusConfig, BioGptConfig, BlenderbotConfig, BlenderbotSmallConfig, BloomConfig, CamembertConfig, LlamaConfig, CodeGenConfig, CohereConfig, Cohere2Config, CpmAntConfig, CTRLConfig, Data2VecTextConfig, DbrxConfig, DiffLlamaConfig, ElectraConfig, Emu3Config, ErnieConfig, FalconConfig, FalconMambaConfig, FuyuConfig, GemmaConfig, Gemma2Config, GitConfig, GlmConfig, GotOcr2Config, GPT2Config, GPT2Config, GPTBigCodeConfig, GPTNeoConfig, GPTNeoXConfig, GPTNeoXJapaneseConfig, GPTJConfig, GraniteConfig, GraniteMoeConfig, GraniteMoeSharedConfig, HeliumConfig, JambaConfig, JetMoeConfig, LlamaConfig, MambaConfig, Mamba2Config, MarianConfig, MBartConfig, MegaConfig, MegatronBertConfig, MistralConfig, MixtralConfig, MllamaConfig, MoshiConfig, MptConfig, MusicgenConfig, MusicgenMelodyConfig, MvpConfig, NemotronConfig, OlmoConfig, Olmo2Config, OlmoeConfig, OpenLlamaConfig, OpenAIGPTConfig, OPTConfig, PegasusConfig, PersimmonConfig, PhiConfig, Phi3Config, PhimoeConfig, PLBartConfig, ProphetNetConfig, QDQBertConfig, Qwen2Config, Qwen2MoeConfig, RecurrentGemmaConfig, ReformerConfig, RemBertConfig, RobertaConfig, RobertaPreLayerNormConfig, RoCBertConfig, RoFormerConfig, RwkvConfig, Speech2Text2Config, StableLmConfig, Starcoder2Config, TransfoXLConfig, TrOCRConfig, WhisperConfig, XGLMConfig, XLMConfig, XLMProphetNetConfig, XLMRobertaConfig, XLMRobertaXLConfig, XLNetConfig, XmodConfig, ZambaConfig, Zamba2Config.
[rank2]: Traceback (most recent call last):
[rank2]:   File "/home/ubuntun/disk7T/zy/code/Other/VLM-R1/src/open-r1-multimodal/src/open_r1/grpo_jsonl.py", line 1073, in <module>
[rank2]:     main(script_args, training_args, model_args)
[rank2]:   File "/home/ubuntun/disk7T/zy/code/Other/VLM-R1/src/open-r1-multimodal/src/open_r1/grpo_jsonl.py", line 1040, in main
[rank2]:     trainer = trainer_cls(
[rank2]:   File "/home/ubuntun/disk7T/zy/code/Other/VLM-R1/src/open-r1-multimodal/src/open_r1/trainer/grpo_trainer.py", line 301, in __init__
[rank2]:     self.ref_model = AutoModelForCausalLM.from_pretrained(model_id, **model_init_kwargs)
[rank2]:   File "/home/ubuntun/anaconda3/envs/VLM/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 567, in from_pretrained
[rank2]:     raise ValueError(
[rank2]: ValueError: Unrecognized configuration class <class 'transformers.models.qwen2_5_vl.configuration_qwen2_5_vl.Qwen2_5_VLConfig'> for this kind of AutoModel: AutoModelForCausalLM.
[rank2]: Model type should be one of AriaTextConfig, BambaConfig, BartConfig, BertConfig, BertGenerationConfig, BigBirdConfig, BigBirdPegasusConfig, BioGptConfig, BlenderbotConfig, BlenderbotSmallConfig, BloomConfig, CamembertConfig, LlamaConfig, CodeGenConfig, CohereConfig, Cohere2Config, CpmAntConfig, CTRLConfig, Data2VecTextConfig, DbrxConfig, DiffLlamaConfig, ElectraConfig, Emu3Config, ErnieConfig, FalconConfig, FalconMambaConfig, FuyuConfig, GemmaConfig, Gemma2Config, GitConfig, GlmConfig, GotOcr2Config, GPT2Config, GPT2Config, GPTBigCodeConfig, GPTNeoConfig, GPTNeoXConfig, GPTNeoXJapaneseConfig, GPTJConfig, GraniteConfig, GraniteMoeConfig, GraniteMoeSharedConfig, HeliumConfig, JambaConfig, JetMoeConfig, LlamaConfig, MambaConfig, Mamba2Config, MarianConfig, MBartConfig, MegaConfig, MegatronBertConfig, MistralConfig, MixtralConfig, MllamaConfig, MoshiConfig, MptConfig, MusicgenConfig, MusicgenMelodyConfig, MvpConfig, NemotronConfig, OlmoConfig, Olmo2Config, OlmoeConfig, OpenLlamaConfig, OpenAIGPTConfig, OPTConfig, PegasusConfig, PersimmonConfig, PhiConfig, Phi3Config, PhimoeConfig, PLBartConfig, ProphetNetConfig, QDQBertConfig, Qwen2Config, Qwen2MoeConfig, RecurrentGemmaConfig, ReformerConfig, RemBertConfig, RobertaConfig, RobertaPreLayerNormConfig, RoCBertConfig, RoFormerConfig, RwkvConfig, Speech2Text2Config, StableLmConfig, Starcoder2Config, TransfoXLConfig, TrOCRConfig, WhisperConfig, XGLMConfig, XLMConfig, XLMProphetNetConfig, XLMRobertaConfig, XLMRobertaXLConfig, XLNetConfig, XmodConfig, ZambaConfig, Zamba2Config.
[rank7]: Traceback (most recent call last):
[rank7]:   File "/home/ubuntun/disk7T/zy/code/Other/VLM-R1/src/open-r1-multimodal/src/open_r1/grpo_jsonl.py", line 1073, in <module>
[rank7]:     main(script_args, training_args, model_args)
[rank7]:   File "/home/ubuntun/disk7T/zy/code/Other/VLM-R1/src/open-r1-multimodal/src/open_r1/grpo_jsonl.py", line 1040, in main
[rank7]:     trainer = trainer_cls(
[rank7]:   File "/home/ubuntun/disk7T/zy/code/Other/VLM-R1/src/open-r1-multimodal/src/open_r1/trainer/grpo_trainer.py", line 301, in __init__
[rank7]:     self.ref_model = AutoModelForCausalLM.from_pretrained(model_id, **model_init_kwargs)
[rank7]:   File "/home/ubuntun/anaconda3/envs/VLM/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 567, in from_pretrained
[rank7]:     raise ValueError(
[rank7]: ValueError: Unrecognized configuration class <class 'transformers.models.qwen2_5_vl.configuration_qwen2_5_vl.Qwen2_5_VLConfig'> for this kind of AutoModel: AutoModelForCausalLM.
[rank7]: Model type should be one of AriaTextConfig, BambaConfig, BartConfig, BertConfig, BertGenerationConfig, BigBirdConfig, BigBirdPegasusConfig, BioGptConfig, BlenderbotConfig, BlenderbotSmallConfig, BloomConfig, CamembertConfig, LlamaConfig, CodeGenConfig, CohereConfig, Cohere2Config, CpmAntConfig, CTRLConfig, Data2VecTextConfig, DbrxConfig, DiffLlamaConfig, ElectraConfig, Emu3Config, ErnieConfig, FalconConfig, FalconMambaConfig, FuyuConfig, GemmaConfig, Gemma2Config, GitConfig, GlmConfig, GotOcr2Config, GPT2Config, GPT2Config, GPTBigCodeConfig, GPTNeoConfig, GPTNeoXConfig, GPTNeoXJapaneseConfig, GPTJConfig, GraniteConfig, GraniteMoeConfig, GraniteMoeSharedConfig, HeliumConfig, JambaConfig, JetMoeConfig, LlamaConfig, MambaConfig, Mamba2Config, MarianConfig, MBartConfig, MegaConfig, MegatronBertConfig, MistralConfig, MixtralConfig, MllamaConfig, MoshiConfig, MptConfig, MusicgenConfig, MusicgenMelodyConfig, MvpConfig, NemotronConfig, OlmoConfig, Olmo2Config, OlmoeConfig, OpenLlamaConfig, OpenAIGPTConfig, OPTConfig, PegasusConfig, PersimmonConfig, PhiConfig, Phi3Config, PhimoeConfig, PLBartConfig, ProphetNetConfig, QDQBertConfig, Qwen2Config, Qwen2MoeConfig, RecurrentGemmaConfig, ReformerConfig, RemBertConfig, RobertaConfig, RobertaPreLayerNormConfig, RoCBertConfig, RoFormerConfig, RwkvConfig, Speech2Text2Config, StableLmConfig, Starcoder2Config, TransfoXLConfig, TrOCRConfig, WhisperConfig, XGLMConfig, XLMConfig, XLMProphetNetConfig, XLMRobertaConfig, XLMRobertaXLConfig, XLNetConfig, XmodConfig, ZambaConfig, Zamba2Config.
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/ubuntun/disk7T/zy/code/Other/VLM-R1/src/open-r1-multimodal/src/open_r1/grpo_jsonl.py", line 1073, in <module>
[rank0]:     main(script_args, training_args, model_args)
[rank0]:   File "/home/ubuntun/disk7T/zy/code/Other/VLM-R1/src/open-r1-multimodal/src/open_r1/grpo_jsonl.py", line 1040, in main
[rank0]:     trainer = trainer_cls(
[rank0]:   File "/home/ubuntun/disk7T/zy/code/Other/VLM-R1/src/open-r1-multimodal/src/open_r1/trainer/grpo_trainer.py", line 301, in __init__
[rank0]:     self.ref_model = AutoModelForCausalLM.from_pretrained(model_id, **model_init_kwargs)
[rank0]:   File "/home/ubuntun/anaconda3/envs/VLM/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 567, in from_pretrained
[rank0]:     raise ValueError(
[rank0]: ValueError: Unrecognized configuration class <class 'transformers.models.qwen2_5_vl.configuration_qwen2_5_vl.Qwen2_5_VLConfig'> for this kind of AutoModel: AutoModelForCausalLM.
[rank0]: Model type should be one of AriaTextConfig, BambaConfig, BartConfig, BertConfig, BertGenerationConfig, BigBirdConfig, BigBirdPegasusConfig, BioGptConfig, BlenderbotConfig, BlenderbotSmallConfig, BloomConfig, CamembertConfig, LlamaConfig, CodeGenConfig, CohereConfig, Cohere2Config, CpmAntConfig, CTRLConfig, Data2VecTextConfig, DbrxConfig, DiffLlamaConfig, ElectraConfig, Emu3Config, ErnieConfig, FalconConfig, FalconMambaConfig, FuyuConfig, GemmaConfig, Gemma2Config, GitConfig, GlmConfig, GotOcr2Config, GPT2Config, GPT2Config, GPTBigCodeConfig, GPTNeoConfig, GPTNeoXConfig, GPTNeoXJapaneseConfig, GPTJConfig, GraniteConfig, GraniteMoeConfig, GraniteMoeSharedConfig, HeliumConfig, JambaConfig, JetMoeConfig, LlamaConfig, MambaConfig, Mamba2Config, MarianConfig, MBartConfig, MegaConfig, MegatronBertConfig, MistralConfig, MixtralConfig, MllamaConfig, MoshiConfig, MptConfig, MusicgenConfig, MusicgenMelodyConfig, MvpConfig, NemotronConfig, OlmoConfig, Olmo2Config, OlmoeConfig, OpenLlamaConfig, OpenAIGPTConfig, OPTConfig, PegasusConfig, PersimmonConfig, PhiConfig, Phi3Config, PhimoeConfig, PLBartConfig, ProphetNetConfig, QDQBertConfig, Qwen2Config, Qwen2MoeConfig, RecurrentGemmaConfig, ReformerConfig, RemBertConfig, RobertaConfig, RobertaPreLayerNormConfig, RoCBertConfig, RoFormerConfig, RwkvConfig, Speech2Text2Config, StableLmConfig, Starcoder2Config, TransfoXLConfig, TrOCRConfig, WhisperConfig, XGLMConfig, XLMConfig, XLMProphetNetConfig, XLMRobertaConfig, XLMRobertaXLConfig, XLNetConfig, XmodConfig, ZambaConfig, Zamba2Config.
[rank0]:[W827 11:47:10.950574903 ProcessGroupNCCL.cpp:1250] Warning: WARNING: process group has NOT been destroyed before we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_process_group to ensure that any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and block the progress of another member of the process group. This constraint has always been present,  but this warning has only been added since PyTorch 2.4 (function operator())
W0827 11:47:10.925000 28212 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 28238 closing signal SIGTERM
W0827 11:47:10.927000 28212 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 28239 closing signal SIGTERM
W0827 11:47:10.927000 28212 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 28240 closing signal SIGTERM
W0827 11:47:10.927000 28212 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 28241 closing signal SIGTERM
W0827 11:47:10.928000 28212 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 28242 closing signal SIGTERM
W0827 11:47:10.928000 28212 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 28244 closing signal SIGTERM
W0827 11:47:10.928000 28212 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 28245 closing signal SIGTERM
E0827 11:47:11.394000 28212 site-packages/torch/distributed/elastic/multiprocessing/api.py:869] failed (exitcode: 1) local_rank: 5 (pid: 28243) of binary: /home/ubuntun/anaconda3/envs/VLM/bin/python

**Comment by yuanzhao-CVLAB** [comment]
I have solved this issue by transfering 'AutoModelForCausalLM' to 'Qwen2_5_VLForConditionalGeneration'.
Specifically, you can rename AutoModelForCausalLM to Qwen2_5_VLForConditionalGeneration in grpo_trainer.py (line 301).
