### ISSUE TITLE
Flash Attention 2.0 with a model not initialized on GPU.  请问一下这是怎么回事

### ISSUE THREAD

**Issue by hqx6** [om-ai-lab/VLM-R1#53]
Loaded 80512 samples from /data/llm/VLM-R1/dataset/rec_jsons_processed/refcocog_train.json
[2025-02-25 14:50:16,063] [INFO] [config.py:733:__init__] Config mesh_device None world_size = 8
You are attempting to use Flash Attention 2.0 with a model not initialized on GPU. Make sure to move the model to GPU after initializing it on CPU with `model.to('cuda')`.

**Comment by hqx6** [comment]
# export CUDA_DEVICE_MAX_CONNECTIONS=1
export NCCL_P2P_DISABLE=1设置了这个好了
另外，什么时候支持其他模型呀，例如[InternVL](https://github.com/OpenGVLab/InternVL)

**Comment by SZhanZ** [comment]
Hello,你好，集成其他模型的功能正在开发中，会在近期内上线~

**Comment by zhaoyuxin2** [comment]
export NCCL_P2P_DISABLE=1
xport CUDA_DEVICE_MAX_CONNECTIONS=1
这两句指令设置在run_grpo_rec.sh中吗？
我设置了这两句但还是出现相同报错

**Comment by davidluciolu** [comment]
> export NCCL_P2P_DISABLE=1 xport CUDA_DEVICE_MAX_CONNECTIONS=1 这两句指令设置在run_grpo_rec.sh中吗？ 我设置了这两句但还是出现相同报错
 same as you

**Comment by Damonzhl** [comment]
> export NCCL_P2P_DISABLE=1 xport CUDA_DEVICE_MAX_CONNECTIONS=1 这两句指令设置在run_grpo_rec.sh中吗？ 我设置了这两句但还是出现相同报错

same as you

**Comment by zhaoyuxin2** [comment]
我查看了下面的报错，是size mismatch的问题，You are attempting to use Flash Attention 2.0 with a model not initialized on GPU. Make sure to move the model to GPU after initializing it on CPU with model.to('cuda').这个似乎不是报错，我按照issue86的方法将transformers版本降为4.49.0解决了这个报错
