### ISSUE TITLE
训练过程中问题

### ISSUE THREAD

**Issue by Nobitaxi** [om-ai-lab/VLM-R1#71]
训练指令：
```
CUDA_VISIBLE_DEVICES=2,3 torchrun --nproc_per_node="2" \
    --nnodes="1" \
    --node_rank="0" \
    --master_addr="127.0.0.1" \
    --master_port="12346" \
    src/open_r1/grpo_rec.py \
    --output_dir outputs/grpo_mllm_model_v1 \
    --model_name_or_path /home/chenxi/models/Qwen2.5-VL-3B-Instruct \
    --dataset_name data_config/rec.yaml \
    --image_root /home/chenxi/LLaMA-Factory/data/ \
    --max_prompt_length 4096 \
    --num_generations 1 \
    --per_device_train_batch_size 1 \
    --gradient_accumulation_steps 8 \
    --logging_steps 1 \
    --bf16 \
    --torch_dtype bfloat16 \
    --data_seed 42 \
    --gradient_checkpointing true \
    --num_train_epochs 1 \
    --save_steps 1000 \
    --save_only_model false
```

报错信息：
```
[rank1]: Traceback (most recent call last):
[rank1]:   File "/home/chenxi/VLM-R1-main/src/open-r1-multimodal/src/open_r1/grpo_rec.py", line 412, in <module>
[rank1]:     main(script_args, training_args, model_args)
[rank1]:   File "/home/chenxi/VLM-R1-main/src/open-r1-multimodal/src/open_r1/grpo_rec.py", line 397, in main
[rank1]:     trainer.train()
[rank1]:   File "/home/chenxi/transformers-main/src/transformers/trainer.py", line 2184, in train
[rank1]:     return inner_training_loop(
[rank1]:   File "/home/chenxi/transformers-main/src/transformers/trainer.py", line 2490, in _inner_training_loop
[rank1]:     tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
[rank1]:   File "/home/chenxi/transformers-main/src/transformers/trainer.py", line 3640, in training_step
[rank1]:     self.accelerator.backward(loss, **kwargs)
[rank1]:   File "/home/chenxi/anaconda3/envs/vlm-r1/lib/python3.10/site-packages/accelerate/accelerator.py", line 2329, in backward
[rank1]:     loss.backward(**kwargs)
[rank1]:   File "/home/chenxi/anaconda3/envs/vlm-r1/lib/python3.10/site-packages/torch/_tensor.py", line 581, in backward
[rank1]:     torch.autograd.backward(
[rank1]:   File "/home/chenxi/anaconda3/envs/vlm-r1/lib/python3.10/site-packages/torch/autograd/__init__.py", line 347, in backward
[rank1]:     _engine_run_backward(
[rank1]:   File "/home/chenxi/anaconda3/envs/vlm-r1/lib/python3.10/site-packages/torch/autograd/graph.py", line 825, in _engine_run_backward
[rank1]:     return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
[rank1]:   File "/home/chenxi/anaconda3/envs/vlm-r1/lib/python3.10/site-packages/torch/autograd/function.py", line 307, in apply
[rank1]:     return user_fn(self, *args)
[rank1]:   File "/home/chenxi/anaconda3/envs/vlm-r1/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 321, in backward
[rank1]:     torch.autograd.backward(outputs_with_grad, args_with_grad)
[rank1]:   File "/home/chenxi/anaconda3/envs/vlm-r1/lib/python3.10/site-packages/torch/autograd/__init__.py", line 347, in backward
[rank1]:     _engine_run_backward(
[rank1]:   File "/home/chenxi/anaconda3/envs/vlm-r1/lib/python3.10/site-packages/torch/autograd/graph.py", line 825, in _engine_run_backward
[rank1]:     return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
[rank1]: RuntimeError: Expected to mark a variable ready only once. This error is caused by one of the following reasons: 1) Use of a module parameter outside the `forward` function. Please make sure model parameters are not shared across multiple concurrent forward-backward passes. or try to use _set_static_graph() as a workaround if this module graph does not change during training loop.2) Reused parameters in multiple reentrant backward passes. For example, if you use multiple `checkpoint` functions to wrap the same part of your model, it would result in the same set of parameters been used by different reentrant backward passes multiple times, and hence marking a variable ready multiple times. DDP does not support such use cases in default. You can try to use _set_static_graph() as a workaround if your module graph does not change over iterations.
[rank1]: Parameter at index 695 with name base_model.model.model.layers.35.mlp.down_proj.lora_B.default.weight has been marked as ready twice. This means that multiple autograd engine  hooks have fired for this particular parameter during this iteration.
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/chenxi/VLM-R1-main/src/open-r1-multimodal/src/open_r1/grpo_rec.py", line 412, in <module>
[rank0]:     main(script_args, training_args, model_args)
[rank0]:   File "/home/chenxi/VLM-R1-main/src/open-r1-multimodal/src/open_r1/grpo_rec.py", line 397, in main
[rank0]:     trainer.train()
[rank0]:   File "/home/chenxi/transformers-main/src/transformers/trainer.py", line 2184, in train
[rank0]:     return inner_training_loop(
[rank0]:   File "/home/chenxi/transformers-main/src/transformers/trainer.py", line 2490, in _inner_training_loop
[rank0]:     tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
[rank0]:   File "/home/chenxi/transformers-main/src/transformers/trainer.py", line 3640, in training_step
[rank0]:     self.accelerator.backward(loss, **kwargs)
[rank0]:   File "/home/chenxi/anaconda3/envs/vlm-r1/lib/python3.10/site-packages/accelerate/accelerator.py", line 2329, in backward
[rank0]:     loss.backward(**kwargs)
[rank0]:   File "/home/chenxi/anaconda3/envs/vlm-r1/lib/python3.10/site-packages/torch/_tensor.py", line 581, in backward
[rank0]:     torch.autograd.backward(
[rank0]:   File "/home/chenxi/anaconda3/envs/vlm-r1/lib/python3.10/site-packages/torch/autograd/__init__.py", line 347, in backward
[rank0]:     _engine_run_backward(
[rank0]:   File "/home/chenxi/anaconda3/envs/vlm-r1/lib/python3.10/site-packages/torch/autograd/graph.py", line 825, in _engine_run_backward
[rank0]:     return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
[rank0]:   File "/home/chenxi/anaconda3/envs/vlm-r1/lib/python3.10/site-packages/torch/autograd/function.py", line 307, in apply
[rank0]:     return user_fn(self, *args)
[rank0]:   File "/home/chenxi/anaconda3/envs/vlm-r1/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 321, in backward
[rank0]:     torch.autograd.backward(outputs_with_grad, args_with_grad)
[rank0]:   File "/home/chenxi/anaconda3/envs/vlm-r1/lib/python3.10/site-packages/torch/autograd/__init__.py", line 347, in backward
[rank0]:     _engine_run_backward(
[rank0]:   File "/home/chenxi/anaconda3/envs/vlm-r1/lib/python3.10/site-packages/torch/autograd/graph.py", line 825, in _engine_run_backward
[rank0]:     return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
[rank0]: RuntimeError: Expected to mark a variable ready only once. This error is caused by one of the following reasons: 1) Use of a module parameter outside the `forward` function. Please make sure model parameters are not shared across multiple concurrent forward-backward passes. or try to use _set_static_graph() as a workaround if this module graph does not change during training loop.2) Reused parameters in multiple reentrant backward passes. For example, if you use multiple `checkpoint` functions to wrap the same part of your model, it would result in the same set of parameters been used by different reentrant backward passes multiple times, and hence marking a variable ready multiple times. DDP does not support such use cases in default. You can try to use _set_static_graph() as a workaround if your module graph does not change over iterations.
[rank0]: Parameter at index 695 with name base_model.model.model.layers.35.mlp.down_proj.lora_B.default.weight has been marked as ready twice. This means that multiple autograd engine  hooks have fired for this particular parameter during this iteration.
  0%|                                                                                                                                                                                      | 0/6870 [01:38<?, ?it/s]
[rank0]:[W226 18:16:39.229499772 ProcessGroupNCCL.cpp:1250] Warning: WARNING: process group has NOT been destroyed before we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_process_group to ensure that any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and block the progress of another member of the process group. This constraint has always been present,  but this warning has only been added since PyTorch 2.4 (function operator())
E0226 18:16:41.150000 3318643 site-packages/torch/distributed/elastic/multiprocessing/api.py:869] failed (exitcode: 1) local_rank: 0 (pid: 3318722) of binary: /home/chenxi/anaconda3/envs/vlm-r1/bin/python
Traceback (most recent call last):
  File "/home/chenxi/anaconda3/envs/vlm-r1/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/chenxi/anaconda3/envs/vlm-r1/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 355, in wrapper
    return f(*args, **kwargs)
  File "/home/chenxi/anaconda3/envs/vlm-r1/lib/python3.10/site-packages/torch/distributed/run.py", line 919, in main
    run(args)
  File "/home/chenxi/anaconda3/envs/vlm-r1/lib/python3.10/site-packages/torch/distributed/run.py", line 910, in run
    elastic_launch(
  File "/home/chenxi/anaconda3/envs/vlm-r1/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 138, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/chenxi/anaconda3/envs/vlm-r1/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 269, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
src/open_r1/grpo_rec.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2025-02-26_18:16:41
  host      : Artemis
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 3318723)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-02-26_18:16:41
  host      : Artemis
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 3318722)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

不是训练一开始就报错，通过我在reward函数中打印中间结果，发现共调用了16次，我将`logging_steps` 设置为1，发现并没有打印，也就是说这16次调用发生在第一个step。所以我的报错是在第一个step结束的时候，但是我不知道这个错误具体是怎么回事，如何解决？

**Comment by xrc10** [comment]
我们没遇到过这个问题。可以报一下transformers和torch的版本吗？

**Comment by Nobitaxi** [comment]
> 我们没遇到过这个问题。可以报一下transformers和torch的版本吗？

```
transformers   4.49.0.dev0
torch          2.5.1
```

**Comment by wen0527zhang** [comment]
解决了吗

**Comment by Nobitaxi** [comment]
> 解决了吗
目前调整了这两个参数：
```
 --fp16 \
 --torch_dtype float16 \
```
把bf16换成fp16，训练暂时没有报这个错了，后续还得观察...

**Comment by luzhaozhang2276** [comment]
请问与上述一样的配置，是否有遇到`Caught signal 8 (Floating point exception: integer divide by zero)`的错误呢？
详细报错信息如下：
```
[lzz-vlm-h20-0:1520757:0:1520757] Caught signal 8 (Floating point exception: integer divide by zero)
BFD: DWARF error: section .debug_info is larger than its filesize! (0x5d4f30 vs 0x4369b8)
BFD: DWARF error: section .debug_info is larger than its filesize! (0x5d4f30 vs 0x4369b8)
==== backtrace (tid:1520757) ====
 0 0x0000000000042520 __sigaction()  ???:0
 1 0x0000000000aff921 cublasLt_for_cublas_ZZZ()  ???:0
 2 0x0000000000837ee3 cublasLt_for_cublas_ZZZ()  ???:0
 3 0x00000000006b5132 cublasLtLegacyGemmUtilizationZZZ()  ???:0
 4 0x000000000078d897 cublasLtMatmulAlgoCheck()  ???:0
 5 0x000000000078e8c5 cublasLtMatmulAlgoCheck()  ???:0
 6 0x000000000078f59e cublasLtMatmulAlgoCheck()  ???:0
 7 0x00000000007def56 cublasLtTSTMatmulAlgoGetHeuristic()  ???:0
 8 0x0000000000869eba cublasXerbla()  ???:0
 9 0x000000000086a96c cublasXerbla()  ???:0
10 0x000000000086cba2 cublasXerbla()  ???:0
11 0x000000000084358f cublasXerbla()  ???:0
12 0x0000000000ac7ecf cublasUint8gemmBias()  ???:0
13 0x0000000000ac83d8 cublasUint8gemmBias()  ???:0
14 0x00000000003e1c7d cublasGemmEx()  ???:0
15 0x000000000301ff0f at::cuda::blas::gemm<c10::BFloat16>()  :0
16 0x0000000003049005 at::native::(anonymous namespace)::addmm_out_cuda_impl()  Blas.cpp:0
17 0x000000000304988a at::native::structured_mm_out_cuda::impl()  ???:0
18 0x0000000002dcc2e0 at::(anonymous namespace)::wrapper_CUDA_mm()  RegisterCUDA.cpp:0
19 0x0000000002dcc350 c10::impl::wrap_kernel_functor_unboxed_<c10::impl::detail::WrapFunctionIntoFunctor_<c10::CompileTimeFunctionPointer<at::Tensor (at::Tensor const&, at::Tensor const&), &at::(anonymous namespace)::wrapper_CUDA_mm>, at::Tensor, c10::guts::typelist::typelist<at::Tensor const&, at::Tensor const&> >, at::Tensor (at::Tensor const&, at::Tensor const&)>::call()  RegisterCUDA.cpp:0
20 0x000000000273579e at::_ops::mm::redispatch()  ???:0
21 0x000000000430f731 torch::autograd::VariableType::(anonymous namespace)::mm()  VariableType_3.cpp:0
22 0x00000000043102f3 c10::impl::wrap_kernel_functor_unboxed_<c10::impl::detail::WrapFunctionIntoFunctor_<c10::CompileTimeFunctionPointer<at::Tensor (c10::DispatchKeySet, at::Tensor const&, at::Tensor const&), &torch::autograd::VariableType::(anonymous namespace)::mm>, at::Tensor, c10::guts::typelist::typelist<c10::DispatchKeySet, at::Tensor const&, at::Tensor const&> >, at::Tensor (c10::DispatchKeySet, at::Tensor const&, at::Tensor const&)>::call()  VariableType_3.cpp:0
23 0x0000000002782b11 at::_ops::mm::call()  ???:0
24 0x0000000001b910d5 at::native::_matmul_impl()  LinearAlgebra.cpp:0
25 0x0000000001b98729 at::native::matmul()  ???:0
26 0x0000000002d059c0 c10::impl::wrap_kernel_functor_unboxed_<c10::impl::detail::WrapFunctionIntoFunctor_<c10::CompileTimeFunctionPointer<at::Tensor (at::Tensor const&, at::Tensor const&), &at::(anonymous namespace)::(anonymous namespace)::wrapper_CompositeImplicitAutograd__matmul>, at::Tensor, c10::guts::typelist::typelist<at::Tensor const&, at::Tensor const&> >, at::Tensor (at::Tensor const&, at::Tensor const&)>::call()  RegisterCompositeImplicitAutograd.cpp:0
27 0x00000000028a4051 at::_ops::matmul::call()  ???:0
28 0x00000000004d101e torch::autograd::THPVariable_matmul()  python_variable_methods.cpp:0
29 0x000000000015b8b7 _PyObject_GetDictPtr()  ???:0
30 0x000000000014345c _PyEval_EvalFrameDefault()  ???:0
31 0x000000000015a9fc _PyFunction_Vectorcall()  ???:0
32 0x00000000001455d7 _PyEval_EvalFrameDefault()  ???:0
33 0x000000000015a9fc _PyFunction_Vectorcall()  ???:0
34 0x00000000007a4ee0 THPFunction_apply()  ???:0
35 0x000000000015a138 PyObject_CallFunctionObjArgs()  ???:0
36 0x000000000016942b PyObject_Call()  ???:0
37 0x00000000001455d7 _PyEval_EvalFrameDefault()  ???:0
38 0x00000000001687f1 PyMethod_New()  ???:0
39 0x0000000000148cfa _PyEval_EvalFrameDefault()  ???:0
40 0x000000000015a9fc _PyFunction_Vectorcall()  ???:0
41 0x0000000000148cfa _PyEval_EvalFrameDefault()  ???:0
42 0x000000000016893e PyMethod_New()  ???:0
43 0x00000000001455d7 _PyEval_EvalFrameDefault()  ???:0
44 0x000000000016893e PyMethod_New()  ???:0
45 0x00000000001455d7 _PyEval_EvalFrameDefault()  ???:0
46 0x000000000014fc14 _PyObject_FastCallDictTstate()  ???:0
47 0x000000000016586c _PyObject_Call_Prepend()  ???:0
48 0x0000000000280700 PyInit__datetime()  ???:0
49 0x0000000000150a7b _PyObject_MakeTpCall()  ???:0
50 0x0000000000149629 _PyEval_EvalFrameDefault()  ???:0
51 0x000000000016893e PyMethod_New()  ???:0
52 0x00000000001455d7 _PyEval_EvalFrameDefault()  ???:0
53 0x000000000016893e PyMethod_New()  ???:0
54 0x00000000001455d7 _PyEval_EvalFrameDefault()  ???:0
55 0x000000000014fc14 _PyObject_FastCallDictTstate()  ???:0
56 0x000000000016586c _PyObject_Call_Prepend()  ???:0
=================================
[2025-02-27 06:26:45,675] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: -8) local_rank: 0 (pid: 1520757) of binary: /usr/bin/python
Traceback (most recent call last):
  File "/usr/local/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 806, in main
    run(args)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
=======================================================
src/open_r1/grpo_rec.py FAILED
-------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
-------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-02-27_06:26:45
  host      : lzz-vlm-h20-0
  rank      : 0 (local_rank: 0)
  exitcode  : -8 (pid: 1520757)
  error_file: <N/A>
  traceback : Signal 8 (SIGFPE) received by PID 1520757
=======================================================
```
这边定位到的问题是`Qwen2_5_VLForConditionalGeneration`模型推理时报错

**Comment by Nobitaxi** [comment]
> 请问与上述一样的配置，是否有遇到`Caught signal 8 (Floating point exception: integer divide by zero)`的错误呢？ 详细报错信息如下：
> 
> ```
> [lzz-vlm-h20-0:1520757:0:1520757] Caught signal 8 (Floating point exception: integer divide by zero)
> BFD: DWARF error: section .debug_info is larger than its filesize! (0x5d4f30 vs 0x4369b8)
> BFD: DWARF error: section .debug_info is larger than its filesize! (0x5d4f30 vs 0x4369b8)
> ==== backtrace (tid:1520757) ====
>  0 0x0000000000042520 __sigaction()  ???:0
>  1 0x0000000000aff921 cublasLt_for_cublas_ZZZ()  ???:0
>  2 0x0000000000837ee3 cublasLt_for_cublas_ZZZ()  ???:0
>  3 0x00000000006b5132 cublasLtLegacyGemmUtilizationZZZ()  ???:0
>  4 0x000000000078d897 cublasLtMatmulAlgoCheck()  ???:0
>  5 0x000000000078e8c5 cublasLtMatmulAlgoCheck()  ???:0
>  6 0x000000000078f59e cublasLtMatmulAlgoCheck()  ???:0
>  7 0x00000000007def56 cublasLtTSTMatmulAlgoGetHeuristic()  ???:0
>  8 0x0000000000869eba cublasXerbla()  ???:0
>  9 0x000000000086a96c cublasXerbla()  ???:0
> 10 0x000000000086cba2 cublasXerbla()  ???:0
> 11 0x000000000084358f cublasXerbla()  ???:0
> 12 0x0000000000ac7ecf cublasUint8gemmBias()  ???:0
> 13 0x0000000000ac83d8 cublasUint8gemmBias()  ???:0
> 14 0x00000000003e1c7d cublasGemmEx()  ???:0
> 15 0x000000000301ff0f at::cuda::blas::gemm<c10::BFloat16>()  :0
> 16 0x0000000003049005 at::native::(anonymous namespace)::addmm_out_cuda_impl()  Blas.cpp:0
> 17 0x000000000304988a at::native::structured_mm_out_cuda::impl()  ???:0
> 18 0x0000000002dcc2e0 at::(anonymous namespace)::wrapper_CUDA_mm()  RegisterCUDA.cpp:0
> 19 0x0000000002dcc350 c10::impl::wrap_kernel_functor_unboxed_<c10::impl::detail::WrapFunctionIntoFunctor_<c10::CompileTimeFunctionPointer<at::Tensor (at::Tensor const&, at::Tensor const&), &at::(anonymous namespace)::wrapper_CUDA_mm>, at::Tensor, c10::guts::typelist::typelist<at::Tensor const&, at::Tensor const&> >, at::Tensor (at::Tensor const&, at::Tensor const&)>::call()  RegisterCUDA.cpp:0
> 20 0x000000000273579e at::_ops::mm::redispatch()  ???:0
> 21 0x000000000430f731 torch::autograd::VariableType::(anonymous namespace)::mm()  VariableType_3.cpp:0
> 22 0x00000000043102f3 c10::impl::wrap_kernel_functor_unboxed_<c10::impl::detail::WrapFunctionIntoFunctor_<c10::CompileTimeFunctionPointer<at::Tensor (c10::DispatchKeySet, at::Tensor const&, at::Tensor const&), &torch::autograd::VariableType::(anonymous namespace)::mm>, at::Tensor, c10::guts::typelist::typelist<c10::DispatchKeySet, at::Tensor const&, at::Tensor const&> >, at::Tensor (c10::DispatchKeySet, at::Tensor const&, at::Tensor const&)>::call()  VariableType_3.cpp:0
> 23 0x0000000002782b11 at::_ops::mm::call()  ???:0
> 24 0x0000000001b910d5 at::native::_matmul_impl()  LinearAlgebra.cpp:0
> 25 0x0000000001b98729 at::native::matmul()  ???:0
> 26 0x0000000002d059c0 c10::impl::wrap_kernel_functor_unboxed_<c10::impl::detail::WrapFunctionIntoFunctor_<c10::CompileTimeFunctionPointer<at::Tensor (at::Tensor const&, at::Tensor const&), &at::(anonymous namespace)::(anonymous namespace)::wrapper_CompositeImplicitAutograd__matmul>, at::Tensor, c10::guts::typelist::typelist<at::Tensor const&, at::Tensor const&> >, at::Tensor (at::Tensor const&, at::Tensor const&)>::call()  RegisterCompositeImplicitAutograd.cpp:0
> 27 0x00000000028a4051 at::_ops::matmul::call()  ???:0
> 28 0x00000000004d101e torch::autograd::THPVariable_matmul()  python_variable_methods.cpp:0
> 29 0x000000000015b8b7 _PyObject_GetDictPtr()  ???:0
> 30 0x000000000014345c _PyEval_EvalFrameDefault()  ???:0
> 31 0x000000000015a9fc _PyFunction_Vectorcall()  ???:0
> 32 0x00000000001455d7 _PyEval_EvalFrameDefault()  ???:0
> 33 0x000000000015a9fc _PyFunction_Vectorcall()  ???:0
> 34 0x00000000007a4ee0 THPFunction_apply()  ???:0
> 35 0x000000000015a138 PyObject_CallFunctionObjArgs()  ???:0
> 36 0x000000000016942b PyObject_Call()  ???:0
> 37 0x00000000001455d7 _PyEval_EvalFrameDefault()  ???:0
> 38 0x00000000001687f1 PyMethod_New()  ???:0
> 39 0x0000000000148cfa _PyEval_EvalFrameDefault()  ???:0
> 40 0x000000000015a9fc _PyFunction_Vectorcall()  ???:0
> 41 0x0000000000148cfa _PyEval_EvalFrameDefault()  ???:0
> 42 0x000000000016893e PyMethod_New()  ???:0
> 43 0x00000000001455d7 _PyEval_EvalFrameDefault()  ???:0
> 44 0x000000000016893e PyMethod_New()  ???:0
> 45 0x00000000001455d7 _PyEval_EvalFrameDefault()  ???:0
> 46 0x000000000014fc14 _PyObject_FastCallDictTstate()  ???:0
> 47 0x000000000016586c _PyObject_Call_Prepend()  ???:0
> 48 0x0000000000280700 PyInit__datetime()  ???:0
> 49 0x0000000000150a7b _PyObject_MakeTpCall()  ???:0
> 50 0x0000000000149629 _PyEval_EvalFrameDefault()  ???:0
> 51 0x000000000016893e PyMethod_New()  ???:0
> 52 0x00000000001455d7 _PyEval_EvalFrameDefault()  ???:0
> 53 0x000000000016893e PyMethod_New()  ???:0
> 54 0x00000000001455d7 _PyEval_EvalFrameDefault()  ???:0
> 55 0x000000000014fc14 _PyObject_FastCallDictTstate()  ???:0
> 56 0x000000000016586c _PyObject_Call_Prepend()  ???:0
> =================================
> [2025-02-27 06:26:45,675] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: -8) local_rank: 0 (pid: 1520757) of binary: /usr/bin/python
> Traceback (most recent call last):
>   File "/usr/local/bin/torchrun", line 8, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python3.10/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
>     return f(*args, **kwargs)
>   File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 806, in main
>     run(args)
>   File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 797, in run
>     elastic_launch(
>   File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 134, in __call__
>     return launch_agent(self._config, self._entrypoint, list(args))
>   File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
>     raise ChildFailedError(
> torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
> =======================================================
> src/open_r1/grpo_rec.py FAILED
> -------------------------------------------------------
> Failures:
>   <NO_OTHER_FAILURES>
> -------------------------------------------------------
> Root Cause (first observed failure):
> [0]:
>   time      : 2025-02-27_06:26:45
>   host      : lzz-vlm-h20-0
>   rank      : 0 (local_rank: 0)
>   exitcode  : -8 (pid: 1520757)
>   error_file: <N/A>
>   traceback : Signal 8 (SIGFPE) received by PID 1520757
> =======================================================
> ```
> 
> 这边定位到的问题是`Qwen2_5_VLForConditionalGeneration`模型推理时报错

暂时还没有遇到过啊...

**Comment by luzhaozhang2276** [comment]
> > 请问与上述一样的配置，是否有遇到`Caught signal 8 (Floating point exception: integer divide by zero)`的错误呢？ 详细报错信息如下：
> >   
> > 这边定位到的问题是`Qwen2_5_VLForConditionalGeneration`模型推理时报错
> 
> 暂时还没有遇到过啊...

已解决，是H20显卡环境配置的问题~

**Comment by Nobitaxi** [comment]
训练过程中犯了一个错误，可能会导致`grad_norm`和`reward_std`都为nan。就是`--num_generations 1`，当时只想着把内存减少一点先跑着试一下，但忘了GRPO的特点，所以`num_generations`最低都要2，才能凑成组间。
